# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatemplate',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
