# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 13:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_templates', '0003_auto_20171031_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatemplate',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
