language: python

python: 2.7

services: postgresql

env:
  - DJANGO=1.11.6

before_install:
  - cd api
  - DJANGO_SETTINGS_MODULE="interestr.interestr.settings"
  - PYTHONPATH="$HOME/builds/bounswe/bounswe2017group5"
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - cd interestr
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py test

notifications:
  email:
    on_success: change
    on_failure: always
