# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_templates', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='data_templates.DataTemplate'),
            preserve_default=False,
        ),
    ]
