# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171027_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contenUrl',
            new_name='content_url',
        ),
    ]
