# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171031_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(default='/static/assets/img/default_group_icon.png', upload_to=b''),
        ),
    ]
