# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171031_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_url',
        ),
    ]
