# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20171031_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
