# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171031_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('concepturi', models.URLField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
