# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171115_2116'),
        ('api', '0010_auto_20171116_1009'),
    ]

    operations = [
    ]
