# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20171116_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(related_name='groups', to='api.Tag'),
        ),
    ]
