# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171119_1159'),
        ('api', '0013_auto_20171128_0939'),
    ]

    operations = [
    ]
