# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171128_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.TextField(),
        ),
    ]
