# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171128_1950'),
        ('api', '0015_merge_20171128_1853'),
        ('api', '0015_auto_20171123_2120'),
    ]

    operations = [
    ]
