# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20171129_2259'),
        ('api', '0018_merge_20171129_2224'),
    ]

    operations = [
    ]
