# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20171130_0247'),
        ('api', '0019_merge_20171130_0851'),
    ]

    operations = [
    ]
