# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 10:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20171130_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
