# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_auto_20171130_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
