# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profilepage_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='api.ProfilePage'),
        ),
    ]
