# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 16:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_auto_20171222_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anno_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='')),
                ('selector', django.contrib.postgres.fields.jsonb.JSONField()),
                ('annotype', models.CharField(choices=[(b'Image', b'image'), (b'Text', b'text')], max_length=40)),
                ('target', models.URLField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_annotation_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
    ]
