# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_annotation_annotype'),
        ('api', '0026_post_tags'),
    ]

    operations = [
    ]
