# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20171228_1230'),
        ('api', '0028_auto_20171228_1222'),
    ]

    operations = [
    ]
