# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 14:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20171228_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='text',
            new_name='bodyValue',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='selector',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='target',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
