# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20171228_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='selector',
            new_name='target',
        ),
    ]
